import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docSidebar: [
    { type: "autogenerated", dirName: "." },
    // "intro",
    // {
    //   type: "category",
    //   label: "Receipts",
    //   items: ["receipts/date"],
    // },
  ],
};

export default sidebars;
